### PR TITLE
Caused the server to crash

### PR DESCRIPTION
**Pull request by VinAdmin**
Added a check for nil.
photo_2024-09-09_12-03-32

### CODE REVIEW

**Comment by OgelGames** [comment]
This won't change anything, nil values are already cancelled out by the `or 0`, and it's not the value that is the problem anyway, it's the table index.

It looks like `minetest.hash_node_position` is returning NaN (not nil), which means the value passed to that function is the problem.

**Comment by VinAdmin** [comment]
After this fix, everything started working correctly.

**Comment by SwissalpS** [comment]
I agree with OgelGames, it's the value in ``h`` that is causing the error.

The reason it worked for you after this patch must be somewhere else. Possibly ``entity._pos`` was invalid in the run that crashed your game.

Please try and find a reliable way to reproduce the crash situation.

(Side-note: seriously a screenshot of text?)

**Comment by VinAdmin** [comment]
> (Примечание: серьезно, скриншот текста?)

Unfortunately, the log file was not saved.

I hoped that the error was not only mine.

**Pull request closed without merging**
