### PR TITLE
Fix autocrafter destroying return items that don't fit in dst

### LINKED ISSUE #61: autocrafter: if there isn't enough room in the output inventory, replacements may be lost
expected behavior: crafting should not occur unless there is room for the output and all replacements simultaneously. 

hopefully these images are enough to demonstrate the problem:

image

image

### PR DESCRIPTION
**Pull request by SwissalpS**
see https://github.com/mt-mods/pipeworks/issues/61

fixes #61

also snuck in two other minor changes

### CODE REVIEW

**Comment by SwissalpS** [comment]
compare with #70 and decide which is better

**Comment by BuckarooBanzay** [comment]
haven't tested it but this looks cleaner :+1:

**Review by S-S-X — APPROVED** [review]
Didn't test but looks fine.

**Comment by SwissalpS** [comment]
closing to give #70 preference, can be reopened if there is reason to.

**Pull request closed without merging**
