### PR TITLE
Fix autocrafter variant 3

### LINKED ISSUE #61: autocrafter: if there isn't enough room in the output inventory, replacements may be lost
expected behavior: crafting should not occur unless there is room for the output and all replacements simultaneously. 

hopefully these images are enough to demonstrate the problem:

image

image

### PR DESCRIPTION
**Pull request by SwissalpS**
This time going the long way of analyzing dst inv and trying to fit items with some logic instead of just blindly adding to each slot.

fixes #61 
replaces #69
replaces #70

Edit: thanks to @fluxionary  and @S-S-X for the valuable input

### CODE REVIEW

**Comment by OgelGames** [comment]
Hmm, that seems like a lot of code to fix a simple problem... 🤔 I also feel like I've fixed this before...

**Comment by OgelGames** [comment]
There, much simpler: #72

**Comment by S-S-X** [comment]
If doing this I'd say generic library should be pulled in and preferably required pipeworks code reduced to just few lines.
But I do not know any good library, futil thing seems to pull more dependencies (besides itself) and probably at least 95% of it isn't needed here for anything.

**Comment by SwissalpS** [comment]
> There, much simpler: #72

Yep, I hadn't gone that route because max_stack issues, but I must have overlooked get_free_space()

Will test it tonight.

**Comment by SwissalpS** [comment]
closing in favour of #72

**Pull request closed without merging**
