### PR TITLE
Store teleport tube DB more compactly

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Entries are now stored in this format:

```
<can receive> ':' <channel>
```

The position is no longer stored in the value, since it is already hashed and used as the key.

With Minetest's current mod storage implementation, this change will reduce memory usage.

### CODE REVIEW

**Review by wsor4035 — APPROVED** [review]
leaving this open for a bit since it is a new storage format

**Comment by fluxionary** [comment]
> With Minetest's current mod storage implementation, this change will reduce memory usage.

i am curious, did you actually measure how much memory this saves? i'm not objecting to this change for any reason, or trying to trivialize it - it clearly reduces some redundancy, and that's a reasonable goal on its own account. but how many teleport tubes do you need for this to have a meaningful effect?

**Comment by TurkeyMcMac** [comment]
Using a copy of the database from Pandorabox, approximately 2.3MB of RAM should be saved. That is, until my patch to Minetest gets accepted, probably before 5.7.

**Comment by S-S-X** [comment]
Bit offtopic but kinda related

To reduce ram consumption significantly take a look at cache, when there was talk about implementing it looked like memory hog so I did some little testing: https://gist.github.com/S-S-X/4bcfcb9c4f433cb8bb15055fdd66d9ef
However better efficiency would require few other changes so simpler caching was implemented, here's also comparison using pandorabox's tp tube db back then:
```
Cache indexing by position:
21912.06640625 KB
18901 entries
Cache indexing by channel:
413.2578125 KB
5112 entries
```

**Comment by fluxionary** [comment]
> Using a copy of the database from Pandorabox, approximately 2.3MB of RAM should be saved. That is, until my patch to Minetest gets accepted, probably before 5.7.

care to link the PR? i'm curious.

**Comment by TurkeyMcMac** [comment]
> > Using a copy of the database from Pandorabox, approximately 2.3MB of RAM should be saved. That is, until my patch to Minetest gets accepted, probably before 5.7.
> 
> care to link the PR? i'm curious.

https://github.com/minetest/minetest/pull/12562

**Comment by fluxionary** [comment]
what about the cost of just using mod_storage directly instead of caching things at all?

**Comment by TurkeyMcMac** [comment]
That might be possible using some metatable magic to preserve backwards compatibility.

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by OgelGames** [comment]
Seems like a good optimization, but I'm not sure if the hash can be used as-is, there might be some data lost here: https://github.com/mt-mods/pipeworks/blob/b190d29d21ace3c283ca56547915af7d6430fc2c/teleport_tube.lua#L11-L13

**Comment by SwissalpS** [comment]
> I'm not sure if the hash can be used as-is, there might be some data lost

if I understand correctly, hash_nod_position() concats the three axis into one long number.

Since tp-tube coordinates should be integers, that would leave 9 chars per axis (plus one for sign), with current MT worldsize limits, this should be fine.

Yes, should be tested to see if all those assumptions actually apply.

**Comment by TurkeyMcMac** [comment]
The precision should be fine. `hash_node_position` uses 48 bits. I tried this in a Lua 5.1 REPL:

```lua
print(("%.30g"):format(2^48-1))
```

That prints the same thing as this:

```lua
print(("%.99g"):format(2^48-1))
```

**Pull request merged**
