### PR TITLE
prevent MCL awards mod crash when player is nil

### PR DESCRIPTION
**Pull request by nonfreegithub**
In MCL when player is nil (maybe when is a fake player) MCL awards crash the server

### CODE REVIEW

**Comment by S-S-X** [comment]
It might also fail in some other cases with fake player depending on configuration if it attempts to do this (from awards):
```lua
		local player = minetest.get_player_by_name(name)
		local one = player:hud_add({
```
This might fail if it is fake player, not nil, has a name but player who owns node isn't online when unlock is executed by fake player and awards.show_mode is not set to chat or formspec.

**Comment by nonfreegithub** [comment]
> Maybe awards should be skipped for fake player?

yes I think so

> But it depends if awards should or shouldn't work on fake player.

I think awards should not work with fake players

**Comment by wsor4035** [comment]
tbh this should be fixed in `MCL awards`, not here

**Comment by corarona** [comment]
I can confirm this does not happen with mcl using up-to-date awards from upstream ( e.g. on https://codeberg.org/mineclonia/mineclonia/pulls/640 ) 

For any testers, this setup recreates the bug (mcla / mcl2 with pipeworks):

* Make a redstone pulse setup with 2 observers facing each other
* build a furnace with a iteminjector and pipes leading out (pipes might not be necessary)
* connect the pulser with the iteminjector
* put fuel and raw iron in the furnace
* log out, log in with another name
* run /awards clear
* (with your setup loaded) see it crash

**Comment by wsor4035** [comment]
quick gander, seems https://codeberg.org/mineclonia/mineclonia/commit/7e3064ef934173b420c97106692c108d5d4047e6 is what fixed it

**Comment by wsor4035** [comment]
with confirmation of a mcl* person, closing this

**Pull request closed without merging**
