### PR TITLE
bugfix autocrafter.lua

### PR DESCRIPTION
**Pull request by SwissalpS**
solves #106 but not for the reason that was assumed. It would be good to check also the crafting method that no cooking, grinding etc. is used

### CODE REVIEW

**Comment by programmerjake** [comment]
I did a basic test, it does resolve the issue encountered in #106

**Comment by OgelGames** [comment]
Works to fix the bug, that's all we really need.

**Comment by programmerjake** [comment]
can a new version be published to contentdb?

**Comment by wsor4035** [comment]
> can a new version be published to contentdb?

it should be auto created tonight

**Pull request merged**
