### PR TITLE
check if machine is protected before trying to break/place a node

### PR DESCRIPTION
**Pull request by fluxionary**
this is slight modification to #42.

to recap:

so as not to trigger protection violations. currently, there is a problem when

1. a player puts down a node breaker in an unprotected area
2. another player protects the area
3. nodes continue to be broken
4. protection violations occur, possibly w/ penalties on the violating player, who can no-longer even dismantle their machine.

### CODE REVIEW

**Comment by SwissalpS** [comment]
this feels even weirder. Unfortunately I currently have no setup to test this out and understand why you are solving your problem this way :/

**Comment by wsor4035** [comment]
please resolve conflicts @fluxionary

**Comment by S-S-X** [comment]
> Unfortunately I currently have no setup to test this out and understand why you are solving your problem this way :/

Eye offset is needed because position of fake player when created is actually `position = vector.subtract(wielder_pos, assumed_eye_pos)` where `wielder_pos` is actual node position.
Similar might be possible using pointed_thing angle (a lot more complicated) but I think this is probably currently already simplest solution (unless new property for node pos is added but that wouldn't follow player api).

**Review by S-S-X — APPROVED** [review]
Have not tested but seems like it should do its job disallowing activation of deployer or node breaker if owner does not have access to said device.

**Review by wsor4035 — APPROVED** [review]

**Comment by fluxionary** [comment]
@wsor4035: as there's clearly some qualms about my solution to this problem, i'd prefer that you not merge things so quickly in the future. i have no issue w/ arguing my position.

**Comment by wsor4035** [comment]
@fluxionary an approval outside of my own...

**Comment by fluxionary** [comment]
]> @fluxionary an approval outside of my own...

ah, so there is. but in general, it's totally fine to give these things at least a day or two before merging them, even w/ approval.

**Pull request merged**
